services:
  - type: web
    name: bliztar-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_URL
        sync: false

  - type: web
    name: bliztar-admin
    runtime: static
    rootDir: admin
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
