services:
  - type: web
    name: bliztar-backend
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_URL
        sync: false

  - type: static
    name: bliztar-admin
    rootDir: admin
    buildCommand: npm ci && npm run build
    staticPublishPath: admin/dist
